import { Link, useParams } from "react-router-dom";
import { AlertTriangle, ExternalLink, ShieldCheck, RefreshCw } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { useSecurity } from "@/hooks/useIntelligence";

export default function Security() {
  const { repositoryId } = useParams<{ repositoryId: string }>();
  const query = useSecurity(repositoryId);
  const data = query.data;
  return <div className="space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-muted-foreground">Repository intelligence</p><h1 className="text-2xl font-semibold tracking-tight">Security</h1><p className="mt-1 text-sm text-muted-foreground">Known vulnerabilities matched by OSV against discovered versions.</p></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => void query.refetch()} disabled={query.isFetching} className="gap-1.5"><RefreshCw className={query.isFetching ? "h-3.5 w-3.5 animate-spin" : "h-3.5 w-3.5"} />Refresh</Button><Button variant="ghost" size="sm" render={<Link to={`/repositories/${repositoryId}`} />}>Back to repository</Button></div></div>
    {query.isLoading ? <Card><CardContent className="space-y-3 p-6"><Skeleton className="h-6 w-1/3" /><Skeleton className="h-20 w-full" /></CardContent></Card> : query.isError || !data?.available ? <Card><CardContent className="flex min-h-48 flex-col items-center justify-center gap-3 text-center"><AlertTriangle className="h-8 w-8 text-amber-500" /><p className="font-medium">Security intelligence could not be refreshed</p><p className="text-sm text-muted-foreground">Core repository analysis remains available.</p></CardContent></Card> : <><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{["Critical", "High", "Moderate", "Low", "Unknown"].map((severity) => <Card key={severity}><CardContent className="p-5"><p className="text-sm text-muted-foreground">{severity}</p><p className="mt-2 text-2xl font-semibold">{data.severity_counts[severity] ?? 0}</p></CardContent></Card>)}</div><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ShieldCheck className="h-4 w-4 text-primary" />{data.vulnerabilities.length ? "Vulnerable dependencies" : "No known vulnerabilities"}</CardTitle></CardHeader><CardContent>{data.vulnerabilities.length === 0 ? <p className="text-sm text-muted-foreground">{data.dependencies_scanned} dependencies were checked by OSV.</p> : <div className="space-y-4">{data.vulnerabilities.map((vulnerability) => <div key={`${vulnerability.package}-${vulnerability.id}`} className="rounded-lg border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-medium">{vulnerability.package} <span className="font-mono text-xs text-muted-foreground">{vulnerability.installed_version}</span></p><p className="mt-1 font-mono text-xs text-muted-foreground">{vulnerability.id}</p></div><Badge variant={vulnerability.severity === "Critical" || vulnerability.severity === "High" ? "destructive" : "secondary"}>{vulnerability.severity}</Badge></div>{vulnerability.summary && <p className="mt-3 text-sm text-muted-foreground">{vulnerability.summary}</p>}{vulnerability.fixed_versions.length > 0 && <p className="mt-2 text-xs text-emerald-700 dark:text-emerald-400">Fixed in {vulnerability.fixed_versions.join(", ")}</p>}{vulnerability.references.length > 0 && <a href={vulnerability.references[0]} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-xs text-primary hover:underline">View advisory <ExternalLink className="h-3 w-3" /></a>}</div>)}</div>}</CardContent></Card></>}
  </div>;
}
